### ISSUE TITLE
Search results found in page with accents are not highlighted

### ISSUE THREAD

**Issue by listedegarde** [RavanH/highlight-search-terms#1]
WordPress internal search function returns the post with “également” even on a search for “egalement” without accent but the Hilite Search Terms plugin in turn ignores “également” when highlighting terms on the results page.

See: https://wordpress.org/support/topic/search-results-found-in-page-with-accents-are-not-highlighted/#post-8848255

A little update on my progress: here's a sample that can convert the search into non-accented letters and successfully highlight.  http://jsfiddle.net/nHGU6/89/

**Comment by listedegarde** [comment]
I have started working on a fix here, but I will not push because I don't have time to finish it right now.  https://github.com/listedegarde/highlight-search-terms/tree/search-with-or-without-accents

  - The oe / œ is still not working.
  - The accents-to-js-console.php just converts WordPres default accent conversion in the terminal so that I can copy/paste into the JS file.

It's "good enough" for me for now, so I'll just be careful not to do any updates until a release is available that includes this or similar code.

**Comment by RavanH** [comment]
Thanks for sharing! :)

**Comment by RavanH** [comment]
Update: I found the WordPress internal function remove_accents() here https://developer.wordpress.org/reference/functions/remove_accents/ which I could consider implementing to modify/append terms to highlight. But I'm not sure how/where/when the internal search actually does such a conversion. It's not mentioned in the docs in any case...

Leaving this ticket open as it's still under considereation :)

**Comment by RavanH** [comment]
Hi @listedegarde have you been able to solve the oe / œ issue yet? 

I've implemented accent lenient search highlighting to the script in the latest release but it is different from your approach. Yours seems to be a closer match to the WordPress core accent and special character filter so it would be preferable over the actual implementation... if the oe / œ issue was fixed :)
