### ISSUE TITLE
Error upon upgrade to Wordpress 5.8.3

### ISSUE THREAD

**Issue by HootanRoosta** [RavanH/highlight-search-terms#13]
Hi We started having problem with highlight-search-term when Wordpress updated to 5.8.3
ANyone know how we need to solve this?
thanks,

This is what we have:
WordPress version 5.8.3
Current theme: Organic Life | Shared by VestaThemes.com (version 2.0) Current plugin: Highlight Search Terms (version 1.8.0) PHP version 7.4.26

This is the error we get:
Error Details
=============
An error of type E_ERROR was caused in line 239 of the file /home/g2g1qer3vaa0/public_html/wp-content/plugins/highlight-search-terms/hlst.php. Error message: Uncaught Error: Call to undefined function is_plugin_active() in /home/g2g1qer3vaa0/public_html/wp-content/plugins/highlight-search-terms/hlst.php:239
Stack trace:
#0 /home/g2g1qer3vaa0/public_html/wp-includes/class-wp-hook.php(303): HLST\load_compat('')
#1 /home/g2g1qer3vaa0/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#2 /home/g2g1qer3vaa0/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /home/g2g1qer3vaa0/public_html/wp-settings.php(600): do_action('wp_loaded')
#4 /home/g2g1qer3vaa0/public_html/wp-config.php(92): require_once('/home/g2g1qer3v...')
#5 /home/g2g1qer3vaa0/public_html/wp-load.php(50): require_once('/home/g2g1qer3v...')
#6 /home/g2g1qer3vaa0/public_html/wp-login.php(12): require('/home/g2g1qer3v...')
#7 {main}
  thrown

**Comment by HootanRoosta** [comment]
I see I'm on 1.8.1. is that the one that it's fixed in?

**Comment by HootanRoosta** [comment]
It's seems to work now.
Thanks a lot.

**Comment by RavanH** [comment]
Thanks for the feedback :)
