### ISSUE TITLE
Button to clear search results from page?

### ISSUE THREAD

**Issue by RayBernard** [RavanH/highlight-search-terms#3]
**The implementation of the plugin is simple in its design, and very effective. I like that the linked pages on my search results page "pass the highlighting" along to the viewed page.**

Where I need flexibility is with viewed pages that contain a large number of search term occurrences throughout the page, such as 5 to 10 per each screen of text. It's a distraction rather than a help.

So I created a button for clearing the search results. I include the button only on pages where I think the content is likely to contain many instances of the likely search terms. The button displays only when search parameters are included in the source URL (obtained from _window.location.href_). This is a low-overhead check.

Clearing the search parameters is accomplished by a simple statement that loads the URL without the search parameters: _location.replace(document.querySelector("link[rel='canonical']").href);_

**MY QUESTION: Can you think of a way for me to get the number of highlighted search items without having to scan the DOM for occurrences of the "mark" tags and then use the "term-N" class assignment of the last occurrence to obtain the count?**

**Comment by RavanH** [comment]
The term-N class does not signify the number of instances one term is found on the page. It's the number of words used in the search query. So if you do a search with only one term, then all of the found instances will have the same **term-0** class. Using two search words then all instances of the second word will have a **term-1** class. It does not matter how many instances are found...
