### ISSUE TITLE
The plugin stopped working in WordPress 5.6

### ISSUE THREAD

**Issue by vkrol** [RavanH/highlight-search-terms#9]
In WordPress 5.6 jQuery has been updated to the latest version (https://make.wordpress.org/support/2020/12/handling-potential-jquery-issues-in-wordpress-5-6/), so `jQuery.support.opacity` is always `undefined` in modern browsers https://github.com/RavanH/highlight-search-terms/blob/master/hlst-extend.js#L127. As a result, the plugin always wraps the search results in the `span` element and the native `mark` element highlighting stopped working.

**Comment by RavanH** [comment]
Hi, yes this is a known issue. A work-around is here https://wordpress.org/support/topic/doesnt-work-with-wordpress-5-6/

Thanks for reporting :) A fix will be released soon.

**Comment by vkrol** [comment]
Thank you! We'll wait for a fix.

**Comment by RavanH** [comment]
Just released!

Thanks again for reminding me :)

**Comment by vkrol** [comment]
Awesome, thanks!
